### ISSUE TITLE
Customize Margins

### ISSUE THREAD

**Issue by JonasKaffenberger** [tudace/tuda_latex_templates#206] opened 2020-07-24 08:53 UTC
Hey, I have one question, i want to customize the margins and according to the TUDA-Examples I set custommargins=true and try to define the margins with the geometry package. Maybe I do something wrong but this really mess up the page layer.(See BSP Seite.pdf) Theres a lot of space between bottom line and bottom page edge. Also the colored "TU-Bars" remain to long.  The file "Correct Margins" show the specification given by our Prof..

[BSP Seite.pdf](https://github.com/tudace/tuda_latex_templates/files/4970964/BSP.Seite.pdf)
[Correct Margins.pdf](https://github.com/tudace/tuda_latex_templates/files/4971000/Correct.Margins.pdf)

Thanks for your help.

\documentclass[
	ngerman,
	accentcolor=9c,
	marginpar=false,
	ruledheaders=section,
	%class=report,
	fontsize=12pt,
	custommargins=true,
	%type=intern,
	%colorback=false,
	%logo=head	
	]{tudapub}
	
\usepackage[english]{babel}
\usepackage[babel]{csquotes}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath}
\usepackage[version=4]{mhchem}
\usepackage{graphicx,epstopdf}
\usepackage{pdfpages}
\usepackage{setspace}
\usepackage{geometry}
\usepackage{chemscheme}

\usepackage[style=chem-angew, backend=bibtex]{biblatex}
%\bibliography{Literatur}
\addbibresource{Literatur.bib}
\usepackage{hologo}
\geometry{
		a4paper,
		top=15mm,
		left=20mm,
		bottom=20mm,	
		right=15mm}

\begin{document}

**Comment by TeXhackse** [comment] 2020-07-29 20:28
You are loading geometry yourself. There is an option to configure TUDaPub to work together with geometry. So you have to set
```
custommargins=geometry
```
instead of `custommargins=true`

This will probably fix the issue. This is why we created this variant.

I can't reproduce your output, so if this doesn't help, please add `\listfiles` in the first line of your document and show me the log.

##### Some additional hints, because you posted your complete preamble

Beside this you should maybe recheck your preamble. You are loading csquotes before loading inputenc (this won't change a lot, because inputenc should be already loaded anyway, but in general it should be loaded before any other package. The fontenc package is already loaded by tudapub (if necessary). And maybe you should update your biblatex backend to biber. Because bibtex is not good in working with unicode.

**Comment by JonasKaffenberger** [comment] 2020-07-30 09:39
Thank you for your detailed answer. I will check this out.

**Comment by TeXhackse** [comment] 2020-08-14 10:54
@JonasKaffenberger 
I'd really appreciate to get a status on this. Because if this is solved I'd like to close the issue,

**Comment by JonasKaffenberger** [comment] 2020-08-14 11:07
Hey, sorry I totally forgot to reply on this topic.

Setting custommargins=geometry work perfectly well. Thanks alot!

**Closed** 2020-08-14 11:07 UTC
