### ISSUE TITLE
Font RobotoCondensed-RegularItalic

### ISSUE THREAD

**Issue by famura** [tudace/tuda_latex_templates#91] opened 2019-11-16 13:22 UTC
I want to compile DEMO-TUDaPhD.tex on my Ubuntu 18.04 machine but receive the following error (from TexStudio)

`fontspec error: "font-not-found" The font "RobotoCondensed-RegularItalic" cannot be found. For immediate help type H <return>. {RobotoCondensed}`

So I ran

`sudo apt-get install fonts-roboto`

but this did not fix the problem. I re-installed the fonts and TexLive completely, sitll the same problem. Next, I looked at [this page](https://fonts.google.com/specimen/Roboto+Condensed) which clames that the font package includes the Regular Italic variant. But after downloading the zip file, it is missing (all other variants are there).

I know that this is not a problem of the template itself. Therefore, I am asking if there is any option to bypass the problem by not using this font? 

Thank you in advance.

**Comment by TeXhackse** [comment] 2019-11-16 13:38
could you attach a complete log file of an example?

**Comment by schoeps** [comment] 2019-11-16 13:41
You could install texlive without using your linux package manager. This is what we typically do. Details are here http://tug.org/texlive/quickinstall.html

**Comment by famura** [comment] 2019-11-16 13:58
Thank you for the quick respond. Here is the log file.

[DEMO-TUDaPhD.log](https://github.com/tudace/tuda_latex_templates/files/3854242/DEMO-TUDaPhD.log)

**Comment by famura** [comment] 2019-11-16 14:01
> You could also install texlive without using your linux package manager. This is what we typically do in my workgroup. Details are here http://tug.org/texlive/quickinstall.html

I followed this installation guide during the re-install. Everything went sine and my old projects compile as usual.

**Comment by schoeps** [comment] 2019-11-16 14:05
So we can close this issue?

**Comment by famura** [comment] 2019-11-16 14:08
Sorry, this was a missunderstanding. I have done the procedure as described in your link, but the problem still occours.

**Comment by schoeps** [comment] 2019-11-16 14:10
Did you set the path correctly? What does `which lualatex` return?

**Comment by famura** [comment] 2019-11-16 14:10
It returns `/usr/bin/lualatex`

**Comment by TeXhackse** [comment] 2019-11-16 14:11
gimme a second, I got an idea

**Comment by TeXhackse** [comment] 2019-11-16 14:15
Well, according to your log and my trail to reproduce it.You are using a 2017 texlive installation. this shoould be able to be updated. 
```
/usr/bin/lualatex
```
probably is a softlink to a location where you outdated installation is placed.

Maybe you have 2 different installations on your system. One installed using tlmgr and one with your package management. 

And since some packages only exist in one of these you mix it up. The font files have been renamed since then. Therefore the font is found as a system font but the package doesn't match. 

Best would be to uninstall all TeX related stuff and reinstall it. If possible the better way would be using the link @schoeps posted.

**Comment by famura** [comment] 2019-11-16 14:21
Indeed, I uninstalled the earlier 2017 texlive version using [this guide](https://tex.stackexchange.com/questions/95483/how-to-remove-everything-related-to-tex-live-for-fresh-install-on-ubuntu) and in the last step it might not ahve cleaned all symlinks.

Well, I will repeat the procedure paying more attention to the symlinks and follow @schoeps link.

Thank you for your help.

**Comment by TeXhackse** [comment] 2019-11-16 14:31
:) great,
Happy TeXing then

**Closed by TeXhackse** 2019-11-16 14:31 UTC
Labels: installation/update
