### ISSUE TITLE
Metadata - Keywords in example not shown properly

### ISSUE THREAD

**Issue by ahueck** [tudace/tuda_latex_templates#173] opened 2020-04-08 10:46 UTC
When using the Demo-TUDaPub.tex approach to set the keywords for the pdf meta data, they appear empty in the final document:
```
\Metadata{
        ....
	keywords=TU Darmstadt \sep Corporate Design \sep LaTeX
}
```
However, this seems to work (tested for the demo and my document on tex live):
```
\Metadata{
        ....
	keywords={TU Darmstadt, Corporate Design, LaTeX}
}
```

**Comment by TeXhackse** [comment] 2020-04-09 12:11
This seems to be a problem of pdfx itself. I will get in touch with the developer.

**Comment by TeXhackse** [comment] 2020-05-01 10:18
We got one step further, but it will take some time until this is resolved …

**Comment by TeXhackse** [comment] 2020-05-02 10:03
@ahueck I am sorry to tell you (and also for myself) that this seems to be no bug. 

Problem is, that there seems to be no viewer which can handle the clean markup of the xmp metadata beside Adobe ones. I bothered the developer for several days now, until we found out, it's a viewer issue, not a metadata one. 

So could it be, that you used another viewer than the Adobe one? In this case, we cannot help, because it's the viewers which don't support this type of metadata field, but they are valid.

**Comment by TeXhackse** [comment] 2020-05-06 07:49
@ahueck could you please check whether it's a viewer issue? or send me a compiled pdf, where you think, this issue applies, to ensure, that it's not a bug.

**Comment by ahueck** [comment] 2020-05-06 10:38
Seems to be a viewer issue annoyingly enough:
- Atril and Okular have trouble correctly displaying an Umlaut (and other meta data). I have to check out the newest versions of these applications, and will notify you.
- Evince (v3.32.0) seems to be able to correctly display everything (even wit \sep)

**Comment by TeXhackse** [comment] 2020-05-06 12:02
> I think it uses the hyperref approach instead of pdfx
Sadly it's not like there are two approaches, there are different types of metadata. So it would be possible to add the data twice. pdfx did that but it would also mean to parse it different for both types. 

The metadata is also encoded correctly, you can check that, by having a look at the xmpi auxiliary file.

Sadly PDF viewers especially opensource ones are a great issue. Adobe Reader works fine, tested that, evince didn't work for me either, but I will recheck my poppler version, because this libary is causing the issue.

So there seems to be nothing more we can do, but support the development of PDF viewers.

**Comment by TeXhackse** [comment] 2020-06-12 10:04
I will close this, because It is not really an issue, but a problem concerning PDF viewers.

**Closed by TeXhackse** 2020-06-12 10:04 UTC
Labels: question
