### ISSUE TITLE
stacked accents: incompatibility between pdfx & amsmath

### ISSUE THREAD

**Issue by elenziat** [tudace/tuda_latex_templates#78] opened 2019-11-13 12:35 UTC
When I use the amsmath package, I get a whole bunch of errors using stacked (multiple) accents (like $\dot{\hat{x}}$). The example below results in the expected pdf but outputs 24 errors. (pdflatex, lualatex and xelatex).

It might be actually more of an amsmath problem, however with scrartcl as documentclass there are no errors.

This (or a similar) problem is described in [https://tex.stackexchange.com/questions/482281/math-accent-symbol-over-parentheses-enclosing-accented-symbol-amsmath](url).

The commented part in the example is the solution proposed by skillmon in the link above (not the first answer). With this workaround/solution there are no error messages.

```
\documentclass[IMRAD=false,DIV=calc]{tudapub}
%\documentclass[]{scrartcl}
	
\usepackage{amsmath}
% \usepackage{amsfonts} % Including amsfonts doesn't change anything in this example

%% ======================================================
%% workaround/solution by skillmon posted here
%% https://tex.stackexchange.com/questions/482281/math-accent-symbol-over-parentheses-enclosing-accented-symbol-amsmath
%\makeatletter
%\protected\def\mathaccentV#1#2#3#4#5%
  %{%
    %\ifmmode
      %\mathaccentV@do{#2}{#3}{#4}{#5}%
    %\else
      %\@xp\nonmatherr@\csname #1\endcsname
    %\fi
  %}
%\def\mathaccentV@do#1#2#3#4%
  %{%
    %\global\let\macc@nucleus\@empty
    %\mathaccent"\accentclass@#1#2#3{#4}\macc@nucleus
  %}
%\makeatother
%% ======================================================

\begin{document}

$\dot{\hat{x}}$

\end{document}
```

**Comment by TeXhackse** [comment] 2019-11-13 12:52
This is a know issue. (Though I never faced it myself, because of defining shortcuts). In this case it is caused by the combination of pdfa and amsmath. It's -- as you already said -- not directly related to tudapub. 

I will think about if I can find a way of working around that, but I actually don't think it's helpful, because maybe this will be reimplemented one day and then the workaround might cause other issues. We will leave this one open, in case someone faces it, and add a hint to to the *known issues*.

**Comment by TeXhackse** [comment] 2020-01-21 14:40
I thought I had already added that note, but you can workaound it by setting `pdfa=false` I am still trying to find time to resolve that.

**Comment by martin-fzd** [comment] 2020-10-29 11:08
I will continue writing here and refer to https://github.com/tudace/tuda_latex_templates/issues/184#issuecomment-622922370
With TeXlive 2020 the problem still exists for me. I have updated all packages via `tlmgr update --all`. Did I missed something?

**Comment by TeXhackse** [comment] 2020-10-29 11:19
No you did not, it simply did not resolve it, since the issue lies somewhere else. 

This is why this issue is still open, so you got to use the workaround or disable pdf/a.

**Comment by martin-fzd** [comment] 2020-10-29 12:19
All right. Where do I have to pass  `pdfa=false`?
When I put it into the "options" for the tudapub class, I'll get this error:
```bash
! Class tudapub Error: You cannot use \Metadata\  with pdfa=false..
```

while this is my setting:

```latex
\documentclass[
	ngerman,
	ruledheaders=chapter,% Ebene bis zu der die Überschriften mit Linien abgetrennt werden, vgl. DEMO-TUDaPub
	class=book,% Basisdokumentenklasse. Wählt die Korrespondierende KOMA-Script Klasse
	thesis={
		% Für kleinere Abschlussarbeiten Siehe DEMO-TUDaThesis
		type=dr,
		dr=rernat
	},
	accentcolor=9c,% Auswahl der Akzentfarbe
	custommargins=true,% Ränder werden mithilfe von typearea automatisch berechnet
	marginpar=false,% Kopfzeile und Fußzeile erstrecken sich nicht über die Randnotizspalte
	%BCOR=5mm,%Bindekorrektur, falls notwendig
%	parskip=half-,%Absatzkennzeichnung durch Abstand vgl. KOMA-Script
	fontsize=11pt,%Basisschriftgröße laut Corporate Design ist mit 9pt häufig zu klein
%	logofile=example-image, %Falls die Logo Dateien nicht vorliegen,
       pdfa = false, % <----Here?!

]{tudapub}
```

**Comment by TeXhackse** [comment] 2020-10-29 12:23
Yes.The position is correct. 
This disables the `\Metadata` command, so you also have to remove that one as well.

It's use is to setup the PDF/A-metadata, which will not be used.
I decided to throw an error instead of ignoring the Metadata to avoid confusion.

**Comment by martin-fzd** [comment] 2020-10-29 12:34
Yes, when disabeling  `\Metadata` things work as expected.
Do you think it would be worthwhile to add the info in the `TUDaPub` documentation for this case, how to configure `hyperref` accordingly, so that the meta data is still set in the PDF?
Especially for many math "heavy" documents the stacked accents are really desirable.

**Comment by TeXhackse** [comment] 2020-10-29 12:39
I am working on improving the documentation. I am aware of the fact, it's not as good as it should be. Especially the fact, that we have different pieces of interformation in the documents. 

But I probably will prefer a general documentation including all parts of tudapub instead of copying this to every single demo file. Especially the issue section.

**Comment by martin-fzd** [comment] 2020-10-29 12:42
I agree. I personally appreciate the references to "ongoing development" by linking to the issues in the class documentation. So far a solution has been found for everything :)

**Comment by TeXhackse** [comment] 2022-03-04 10:20
Oh This one is resolved in current versions of TeX Live. :)

**Comment by lueck1803** [comment] 2022-12-25 08:36
Hi,
as you already mentioned, its a conflict between amsmath and pdfx. The new version of amsmath uses a definition pdfx does not know.
The following redefinition solves the problem of nested accents.

`\makeatletter
\AtBeginDocument{\let\mathaccentV\AMS@mathaccentV}
\makeatother`

Have nice holidays.

Kind regards
Lukas Walter

**Comment by TeXhackse** [comment] 2022-12-25 10:55
thanks - Thing is we cannot replace this as long as people are relying on older versions, that's why I did not yet do anything about it, 

The plan for the next major release is to remove pdfx anyway and replace it by the kernels own pdfmanagement mechanism.

**Comment by lueck1803** [comment] 2022-12-25 11:21
That sounds nice.

For those who have this problem and don't want to use \textbf for vectors, use other amsmath features and also need pdfa, can add this in their preamble so far.

**Comment by evamvid** [comment] 2023-02-02 19:57
@TeXhackse I don't know if this is the right place for it, but I thought since we're talking about pdfx here I might as well (instead of opening a new issue since this isn't directly related to the template) -- adding my aufgabenstellung as a pdfpages include has completely broken the PDFA compliance because PDFX doesn't seem to know how to deal with the fonts from the imported PDF, even after I manually embedded them into the pdf of the Aufgabenstellung. 

I'm validating my PDFA compatibility with verapdf, and getting an error that says "If the FontDescriptor dictionary of an embedded CID font contains a CIDSet stream, then it shall identify all CIDs which are present in the font program, regardless of whether a CID in the font is referenced or used by the PDF or not."

The font table for the PDF is this:

```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
KKKIUW+XCharter-Roman                CID Type 0C       Identity-H       yes yes yes     13  0
LUNMMF+Roboto-Regular                CID Type 0C       Identity-H       yes yes yes     14  0
QMJPLU+Roboto-Bold                   CID Type 0C       Identity-H       yes yes yes     20  0
MAYIVC+FrontPagePro-Medium           CID TrueType      Identity-H       yes yes yes     39  0
KYIDZT+SymbolMT                      CID TrueType      Identity-H       yes yes yes     40  0
PGCUGW+Charter-Bold                  TrueType          WinAnsi          yes yes no      41  0
DAESFN+FrontPageMedium               TrueType          WinAnsi          yes yes no      42  0
KUYJMB+FrontPagePro-Medium           TrueType          WinAnsi          yes yes no      43  0
IJGRYF+Charter                       TrueType          WinAnsi          yes yes no      44  0
BHNTXR+Stafford                      TrueType          WinAnsi          yes yes no      45  0
GUTOKG+ArialMT                       Type 1C           WinAnsi          yes yes no      46  0
AIWZML+XCharter-Bold                 CID Type 0C       Identity-H       yes yes yes    120  0
FMADMD+XCharter-Italic               CID Type 0C       Identity-H       yes yes yes    172  0
KEZTQT+RobotoMono-Regular            CID Type 0C       Identity-H       yes yes yes    212  0
```

Do you happen to have any ideas about how I can go about fixing it, or in other words, what I need to do to the Aufgabenstellung PDF to get pdfx to handle its fonts properly? Thanks!

**Comment by TeXhackse** [comment] 2023-12-13 11:22
It took long … I know … but actually the tests are finished so far and the mechanism to use pdfmanagement for the PDF/A creation is currently on a separate branch. In case you want to try it, feel free. Plan is to include that change into version 4.0 which should be released until end of the year.

**Comment by TeXhackse** [comment] 2024-07-03 12:18
As we finally received an update here this is no longer an issue!

**Closed by TeXhackse** 2024-07-03 12:18 UTC
Labels: question
