### ISSUE TITLE
Incomplete \iffalse in tudaexercise.cls

### ISSUE THREAD

**Issue by AlexVHopp** [tudace/tuda_latex_templates#114] opened 2019-12-06 10:48 UTC
When trying to hide the solution in an exercise file, I get an error message of the form
`! Incomplete \iffalse; all text was ignored after line 14`
This happens if I use the global option and if I try to only hide one solution.
Here is a minimal example where this problem occurred for me.

```
\documentclass[a4paper, solution=false]{tudaexercise}

\usepackage[english]{babel}

\begin{document}

\title{Dummy}

\maketitle

\begin{task}{Dummy Task}
	Dummy task
	
\begin{solution}
	Dummy Solution
\end{solution}
\end{task}

\end{document}
```

**Comment by TeXhackse** [comment] 2019-12-09 17:14
Thanks for the report. This results form the reimplementation to make verbatim material in the solution environment possible. I will mix up both implementations, then we get it back working.

**Comment by TeXhackse** [comment] 2019-12-09 17:41
I will run some tests for special cases. Fix will be included in the next update.

**Closed** 2019-12-17 17:02 UTC
Labels: bug

**Comment by AlexVHopp** [comment] 2020-02-10 09:22
Since the newest update, I have the exact same problem again.

**Comment by TeXhackse** [comment] 2020-02-10 09:26
I cannot reproduce this. Can you please attach/send me a log file?

**Comment by AlexVHopp** [comment] 2020-02-10 09:37
I found the problem by myself.
It is not a problem related to the package but due to the fact that updating my system messed with different versions that were on my computer.
