### ISSUE TITLE
double accents in math mode

### ISSUE THREAD

**Issue by flea-rian** [tudace/tuda_latex_templates#184] opened 2020-05-02 07:31 UTC
Hi,
the new package is great, thank's a lot!
After converting everthing from tudthesis to tudapub I have experienced that double accents in math mode no longer work, e.g.

` $\hat{\dot{x}}$`

leads to numerous errors.

```shell
! Missing number, treated as zero.
<to be read again> 
                   \advance 
l.171 $\hat{\dot{x}}
                    $
....
! Illegal unit of measure (pt inserted).
<to be read again> 
                   \advance 
l.171 $\hat{\dot{x}}
                    $
```
Is there any possibility to use double accents?
Thanks!

[DblAccent.log](https://github.com/tudace/tuda_latex_templates/files/4567270/DblAccent.log)

**Comment by TeXhackse** [comment] 2020-05-02 08:48
Thanks for the kind words.

Duplicate of #78 
There you find a workaround and some more information.

**Closed by TeXhackse** 2020-05-02 08:48 UTC

**Comment by flea-rian** [comment] 2020-05-02 09:06
Thanks! Sorry for duplicate, I searched for the wrong keywords then

**Comment by schoeps** [comment] 2020-05-02 09:11
@TeXhackse the issue at https://github.com/latex3/latex2e/issues/216 is closed, should this be fixed in texlive 2020?
