### ISSUE TITLE
DEMO-TUDaThesis.tex errors when compiling with Texmaker

### ISSUE THREAD

**Issue by 1lyass** [tudace/tuda_latex_templates#271] opened 2020-12-10 17:22 UTC
Hi,

when i try to compile the **DEMO-TUDaThesis.tex** with **Texmaker** it gives me the issues:

**1**: ! Undefined control sequence.
<argument> \LaTeX3 error:
Misplaced equals sign in key-value input on line 194
l.194 \Module@Process@SpecialOptions[ptxcd/pub]
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**2**: ! Undefined control sequence.
\xmp@Title ->\protect \vspace {10mm}\thesisTitel
\vspace {5mm}
l.2855 \includexmp{\xmp@template}
%
The control sequence at the end of the top line
of your error message was never \def'ed. If you have
misspelled it (e.g., `\hobx'), type `I' and the correct
spelling (e.g., `I\hbox'). Otherwise just continue,
and I'll forget about whatever was undefined.

**3**:! TeX capacity exceeded, sorry [input stack size=5000].
<argument> \L8U\~
l.2855 \includexmp{\xmp@template}
%
If you really absolutely need more capacity,
you can ask a wizard to enlarge me.

**4**:avail lists: 2:2,4:1,5:10,7:20,9:1,11:3
40560 multiletter control sequences out of 65536+200000
83 fonts using 14078039 bytes
5000i,3n,4007p,10661b,1893s stack positions out of 5000i,500n,10000p,200000b,50000s
! ==> Fatal error occurred, no output PDF file produced!

I deleted Miktex 2.9 multiple times this week and installed it again. I checked the updates installed the **tuda-ci** package. When i compile the **DEMO-TUDaThesis.tex**, Texmaker begins to install the packages and then stops with the errors i mentioned ealier.

I hope someone can help.

**Comment by TeXhackse** [comment] 2020-12-10 17:28
Do you now have an updated MikTeX or still 2.9? 
Did you try to delete the auxilary files after updating the MikTeX installation and recompile afterwards?

I'd need to have more information because the demo file is working fine on recent MikTeX installations. Could you attach a log file?

**Comment by 1lyass** [comment] 2020-12-10 17:36
Yes i have the newest Miktex version.
I deleted the folder in C:Programm/Miktex and deinstalled Miktex.

**Comment by TeXhackse** [comment] 2020-12-10 17:40
Inside the working directory.
Especially the *.xmpdata and the *.aux file should be deleted to ensure you don't use data of an outdated variant. There you would also find the requested log-File.

**Comment by 1lyass** [comment] 2020-12-10 17:55
I deleted the .xmpdata and .aux files and now it gives me different and a lot more errors than before.
There isnt a *.log file only a *lot and *.lof file

**Comment by TeXhackse** [comment] 2020-12-10 19:24
The first error showing up is complaining about a missplaced equals sign, this means that some options are not parsed correctly. Please check, if there is a missing comma in the class options, so 
```
\documentclass[<key>=<value>, <key=value>]{tudapub}
```
Sometimes it happens, that people use it like this:
```https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.de.jsp
\documentclass[
key=value
key=value
]{tudapub}
```

In the latter case there's a comma missing between the first and the second option, this leads to a missplaced equal sign, because TeX wants to use `key=value key=value` as  one option including a second equal sign.

The directly following errors seem to be caused by the first one. (At least as far I can see with not knowing the code.)

The only other error I get is the one about the missing logo file, you can get the files + Instructions at https://www.ce.tu-darmstadt.de/ce/latex_tuda/index.de.jsp or use the `logofile=example-image` as used by the demo.

**Comment by 1lyass** [comment] 2020-12-11 09:50
The only error i get now is that the logo file is missing but I already put the folder with the logo in C: Programm\logo where also the Miktex-folder is. I also added the path of the logo-folder in Miktex-console.

**Comment by TeXhackse** [comment] 2020-12-11 10:21
Did you update the filename-database afterwards? If you did the only idea I have atm is the directory structure.

If I remember correctly, the directory structure also has to serve the TDS (TeX Directory Structure) this means if you add `c:\Programm\logo` as source path, the logo file has to be inside `c:\Programm\logo\tex\latex\` for a better overview one would use `<directory added to MikTeX>/tex/latex/tuda-ci/tuda_logo.pdf`.

You can find the logo including the directory structure via the link above (direct link to the TDS structure: https://download.hrz.tu-darmstadt.de/protected/CE/TUDa_LaTeX/logo_bundle.zip)

**Comment by 1lyass** [comment] 2020-12-12 21:22
It works now. Thank you for your help. 
When i want to include the thesistype do i have to write this code?:  **\thesistype \text{} by \authors  \\**

**Comment by TeXhackse** [comment] 2020-12-12 23:03
I don't mean what you mean with „include the thesitsype“ Do you want to reference it? 

Internally it's saved to the macro `\ptxcd_thesisType`. You could use that using `\csname ptxcd_thesisType\endcsname` If you want to reference the whole string including the type and author information, that's saved to the title field `\@subject`. Maybe you can explain to me what you are planning to do, and I can give you a hint on the best way to achieve that.

**Comment by TeXhackse** [comment] 2020-12-18 11:59
@1lyass I'll close this issue, because it seems like we solved it, if you have further questions, don't be scared to ask / open a new issue.

**Closed by TeXhackse** 2020-12-18 11:59 UTC
Labels: installation/update

**Comment by 1lyass** [comment] 2021-01-23 15:43
Hi,
when i did an updated in the the Miktex Console, Texmaker didnt compile. So i deinstalled Texmaker and Miktex. After installing it again it gives me the same error. There is also no .log file. Here is a picture of the error.
![Screenshot (4)](https://user-images.githubusercontent.com/75802671/105606510-23172c00-5d9a-11eb-8e94-deea110b8d52.png)

**Comment by schoeps** [comment] 2021-01-23 15:55
Please try to install the package "urcls".

**Comment by 1lyass** [comment] 2021-01-23 16:01
I installed it. It gives me the same error.

**Comment by schoeps** [comment] 2021-01-23 16:13
You are missing packages.... It seems that you installed a minimal version of miktex while we recommend to install everything. I think that miktex can somehow automatically install missing dependencies. Unfortunately I do not how to enable this since I am not using miktex/windows. Please use google to find out to do install everything or missing dependencies automatically. It makes no sense for us to discuss package after package (it's [scrreprt](https://www.ctan.org/pkg/scrreprt) this time) since it can be easily hundreds....

**Comment by WangGeng77** [comment] 2021-04-10 13:47
> Hi,
> 
> when i try to compile the **DEMO-TUDaThesis.tex** with **Texmaker** it gives me the issues:
> 
> **1**: ! Undefined control sequence.
> \LaTeX3 error:
> Misplaced equals sign in key-value input on line 194
> l.194 \Module@Process@SpecialOptions[ptxcd/pub]
> The control sequence at the end of the top line
> of your error message was never \def'ed. If you have
> misspelled it (e.g., `\hobx'), type `I' and the correct
> spelling (e.g., `I\hbox'). Otherwise just continue,
> and I'll forget about whatever was undefined.
> 
> **2**: ! Undefined control sequence.
> \xmp@Title ->\protect \vspace {10mm}\thesisTitel
> \vspace {5mm}
> l.2855 \includexmp{\xmp@template}
> %
> The control sequence at the end of the top line
> of your error message was never \def'ed. If you have
> misspelled it (e.g., `\hobx'), type `I' and the correct
> spelling (e.g., `I\hbox'). Otherwise just continue,
> and I'll forget about whatever was undefined.
> 
> **3**:! TeX capacity exceeded, sorry [input stack size=5000].
> \L8U~
> l.2855 \includexmp{\xmp@template}
> %
> If you really absolutely need more capacity,
> you can ask a wizard to enlarge me.
> 
> **4**:avail lists: 2:2,4:1,5:10,7:20,9:1,11:3
> 40560 multiletter control sequences out of 65536+200000
> 83 fonts using 14078039 bytes
> 5000i,3n,4007p,10661b,1893s stack positions out of 5000i,500n,10000p,200000b,50000s
> ! ==> Fatal error occurred, no output PDF file produced!
> 
> I deleted Miktex 2.9 multiple times this week and installed it again. I checked the updates installed the **tuda-ci** package. When i compile the **DEMO-TUDaThesis.tex**, Texmaker begins to install the packages and then stops with the errors i mentioned ealier.
> 
> I hope someone can help.

Hi 1lyass,
Have you fixed the first problem? I am now having the exactly the same problem...

**Comment by TeXhackse** [comment] 2021-04-10 14:07
@WangGeng77  For the upper issue there was a package missing. It's part of the urcls-bundle. It's part of MikTeX & TeX Live, so you can install it easily. 

https://ctan.org/pkg/urcls

In case you have a similar issue which is not exactly the same please open a new issue and we will try to help out.
