### ISSUE TITLE
Metadata problem

### ISSUE THREAD

**Issue by EthanSun-arch** [tudace/tuda_latex_templates#136] opened 2020-01-21 13:42 UTC
If i want to compile the DEMO-TUDAThesis.tex file, I get the following errors: 
"Package TUDaPub Error: You used the title metadata entry." 
"Package TUDaPub Error: You used the author metadata entry."
"Package TUDaPub Error: You used the publisher metadata entry."
"Package TUDaPub Error: You used the creator metadata entry."

I tried that with a fresh installed version of miktex where it didn't  work and the DEMO-TUDAThesis.tex file worked with the previously installed version 2.03a of TUDA-CI package on a different PC and after updating it to 2.05 it didn't worked.
But the compiled PDF contains the changes which I write down.

**Comment by TeXhackse** [comment] 2020-01-21 14:32
Duplicate of 131#

I'll leave this one open, since #131 is in German. 
There is a workound on https://github.com/tudace/tuda_latex_templates/commit/53f44bcf0117f3f3d1b2e6f60221dc785e5c2de9 , but I am still thinking about whats the best way to resolve, it currently seems to be caused by an l3kernel bug which might be fixed, but I got to recheck that. 

If not necessary, you can set `pdfa=false` to not use the XMP metadata at all.

**Comment by EthanSun-arch** [comment] 2020-01-21 14:38
how do i include the pdfa=false into document?
i tried that but i think i did it wrong

**Closed** 2020-01-28 20:40 UTC
Labels: bug
