### ISSUE TITLE
Marginpar notes not aligned to text

### ISSUE THREAD

**Issue by miterion** [tudace/tuda_latex_templates#169] opened 2020-04-01 13:06 UTC
While searching for a way to use the marginpar notes, I noticed that the note text is not aligned to the base text:
![image](https://user-images.githubusercontent.com/4395770/78139728-4054c580-7429-11ea-9d84-7196f693df4a.png)
In my opinion it would look better if a note would appear on the same baseline as the text in which it was declared. Would it be possible to implement that?

If it can not be implemented, it would be nice if the following workaround I found could be mentioned in the documentation.

```latex
% ...
\usepackage{scrlayer-notecolumn}
\setkomafont{notecolumn.marginpar}{\accentfont}
\addtokomafont{notecolumn.marginpar}{\color{textaccentcolor}}

% ...

\makenote{Beispiel für eine Randnotiz}
```
This generates the following margin note:
![image](https://user-images.githubusercontent.com/4395770/78140414-45664480-742a-11ea-98ce-c4702b9f34e3.png)

**Comment by TeXhackse** [comment] 2020-04-06 17:08
Sorry, this was caused by the `\color` command being called in `\vmode`. Fixed that. Will be included in the next release.

So the workaround without an extra package would be:
```
\setkomafont{marginpar}{\leavevmode\accentfont\color{textaccentcolor}}
```

**Closed** 2020-04-25 14:19 UTC
Labels: bug
