### ISSUE TITLE
pdfx package error

### ISSUE THREAD

**Issue by BPollicino** [tudace/tuda_latex_templates#474] opened 2024-06-24 09:49 UTC
![image](https://github.com/tudace/tuda_latex_templates/assets/62886054/b01577f4-bf64-4367-8a22-cc6b9e2987f3)

Hi,
i just updated MikTex / TeXStudio etc. today and after compiling my PhD thesis document (which compiled just fine last week) i got the error messages above.
Following through the errors, the following packages are missing: xmpincl -> ifpdf & ifthen
Trying to update MikTex is the following error, which only occured after the recent update:

![image](https://github.com/tudace/tuda_latex_templates/assets/62886054/6fbc2281-1583-4242-a81e-1ed478fe1d48)

Other forums suggest a prompt update of miktex via "miktek packages update", which I did several times now, also reinstalled miktex. I found no solution until now.
Currently the document is compiling and is displayed but without any citation / biber run.

Maybe this is a familiar problem and someone got a idea for solution.

Thanks in advance.

**Comment by TeXhackse** [comment] 2024-06-24 09:52
That's a duplicate of #472 

You can turn set `pdfa=false` and use the mechanism shown in the current version of the templates:

```
\DocumentMetadata{
	pdfstandard=a-2b,
	pdfversion=1.7,% 2.0 is possible as well, but some validators don't support that yet
}
```

**Comment by BPollicino** [comment] 2024-06-24 10:03
Thanks, this worked!
Now there's just a message "lualatex: major issue: User/administrator updates are out-of-sync." left. Could this become a problem?

**Closed** 2024-07-02 06:36 UTC
Labels: workaround, dependency
