### ISSUE TITLE
Font problems when using fontawesome icon package

### ISSUE THREAD

**Issue by davidgengenbach** [tudace/tuda_latex_templates#175] opened 2020-04-17 00:12 UTC
With the current version, `2.09 (2020/03/13)`, the  theme does not work with the `fontawesome` package anymore, see https://www.overleaf.com/read/vbfzsfzkrvwq.
`\usepackage{fontawesome5}` seems to work.

If the incompatibility can not be fixed, a warning/error would be nice.

By the way: thanks for providing nice support for the templates! This issue tracker actually helped me track down some of my own problems.

**WITH** `\usepackage{fontawesome}`: 
![Screenshot_2020-04-17_02:02:48](https://user-images.githubusercontent.com/2621491/79517829-a8bdbc80-804f-11ea-86f3-b5f3586eaf4f.png)
**WITHOUT** `\usepackage{fontawesome}`:
![Screenshot_2020-04-17_02:02:22](https://user-images.githubusercontent.com/2621491/79517833-abb8ad00-804f-11ea-9d8c-9023f87f00e2.png)

**Comment by TeXhackse** [comment] 2020-04-17 05:32
I cannot reconstruct it outside Overleaf, will try inside Overleaf later.

Anyway:
It's probably caused by fontawesome5 enforcing fontspec if possible. It does not offer an Option to change that, but the tuda-ci bundle requires Type1 fonts for PDF/A comptability. (This is a font-specific issue).
You can use `pdfa=false` for a temporary workaround and I will think about the issue.

**Comment by davidgengenbach** [comment] 2020-04-17 11:09
> It's probably caused by fontawesome5 enforcing fontspec if possible.

The 'fontawesome**5**' package works fine, the 'fontawesome' package does not!

The fontawesome5 package just spurts out a lot of warnings but seems to work otherwise:
```
Package microtype Warning: Unknown slot number of character `\`A' in font encoding `TU' in inheritance list `microtype.cfg/376(protrusion)'.
```

**Comment by TeXhackse** [comment] 2020-04-24 19:19
Sorry, didn't see that you tried both.

fontawesome tells you, that it requires XeLaTeX or LuaLaTeX used. This is because of fontspec. And due to the previously described issue with PDF/A we don't use fontspec, if `pdfa=true`. There's nothing which can be changed. 

The issue about both is actually the same but one can hack fontawesome5 by doing this:
```
\ExplSyntaxOn
\str_new:N \l_save_engine_str 
\cs_set_eq:NN \l_save_engine_str \c_sys_engine_str %save the real engines name to a tmp string 
\cs_undefine:N \c_sys_engine_str
\str_const:Nn \c_sys_engine_str {pdftex} %make fontawesome5 think it's working with pdftex
\ExplSyntaxOff
\usepackage{fontawesome5} %load only fontawesome 5 during this
\ExplSyntaxOn
\cs_undefine:N \c_sys_engine_str
\str_const:Nx \c_sys_engine_str {\l_save_engine_str} %restore the original engine name
\ExplSyntaxOff
```

**Comment by davidgengenbach** [comment] 2020-04-24 19:49
Thank you for the throughout explanation.
I resorted to ignoring the warnings since they do not seem to have any impact on the fonts

```tex
\usepackage{silence}
\WarningFilter{microtype}{Unknown slot number of character}
```

**Comment by TeXhackse** [comment] 2020-04-24 20:58
You might receive an invalid PDF/A. Then you could also disable pdfa-mode to „solve“ it.

**Comment by TeXhackse** [comment] 2020-04-27 18:40
I close this, since it's not directly related to tuda-ci. It's rather a problem of fontawesome enforcing fontspec for luatex.

**Closed by TeXhackse** 2020-04-27 18:40 UTC
